In [2]:
import pandas as pd
import config
df = pd.read_csv(config.RAW_DATA)
df.shape

(23201, 32)

In [3]:
df.info

<bound method DataFrame.info of        job_id                                        job_title  \
0           1                                   Data Scientist
1           2                                   Data Scientist
2           3                         Analytics Data Scientist
3           4                                   Data Scientist
4           5             Sr. Artificial Intelligence Engineer
...       ...                                              ...
23196   23197                       Python Developer-Hyderabad
23197   23198                                 Python Developer
23198   23199  Walk in Interview Python Developer II Hyderabad
23199   23200                                 Python Developer
23200   23201                                 Python Developer

                          company_name  company_rating  \
0                                Cisco             4.1
1                      Caterpillar Inc             4.1
2            Foreign IT Consulting MNC             3.6
3      Fortune 500 IT Services Company             3.6
4        Fortune 500 Product-based MNC             3.6
...                                ...             ...
23196                          Infosys             3.5
23197                           Accufy             3.6
23198        Tata Consultancy Services             3.3
23199                        Mediamint             2.8
23200           CMM Level 5 IT Company             3.6

                                  location scraped_city     role_category  \
0                                Bengaluru    Bangalore    Data Scientist
1                                Bengaluru    Bangalore    Data Scientist
2            Hyderabad, Chennai, Bengaluru    Bangalore    Data Scientist
3                        Mumbai, Bengaluru    Bangalore    Data Scientist
4                          Pune, Bengaluru    Bangalore    Data Scientist
...                                    ...          ...               ...
23196                   Hybrid - Hyderabad    Hyderabad  Python Developer
23197                            Hyderabad    Hyderabad  Python Developer
23198  Hyderabad, Pune, Mumbai (All Areas)    Hyderabad  Python Developer
23199                   Hybrid - Hyderabad    Hyderabad  Python Developer
23200                            Hyderabad    Hyderabad  Python Developer

      experience_raw  experience_min_yrs  experience_max_yrs  ...  scraped_at  \
0           7-10 Yrs                 7.0                10.0  ...  2025-06-10
1            4-8 Yrs                 4.0                 8.0  ...  2025-06-10
2            4-9 Yrs                 4.0                 9.0  ...  2025-06-10
3          10-14 Yrs                 0.0                 0.0  ...  2025-06-10
4           5-10 Yrs                 5.0                10.0  ...  2025-06-10
...              ...                 ...                 ...  ...         ...
23196        2-7 Yrs                 2.0                 7.0  ...  2025-06-10
23197        0-4 Yrs                 0.0                 4.0  ...  2025-06-10
23198         13 Jun                13.0                 8.0  ...  2025-06-10
23199        3-5 Yrs                 3.0                 5.0  ...  2025-06-10
23200       7-12 Yrs                 7.0                12.0  ...  2025-06-10

              salary_tier          experience_tier  is_senior primary_city  \
0             Undisclosed         Senior (6-8 Yrs)      False    Bangalore
1             Undisclosed            Mid (3-5 Yrs)      False    Bangalore
2             Undisclosed            Mid (3-5 Yrs)      False    Hyderabad
3             Undisclosed                  Fresher      False       Mumbai
4             Undisclosed            Mid (3-5 Yrs)       True         Pune
...                   ...                      ...        ...          ...
23196         Undisclosed         Junior (0-2 Yrs)      False    Hyderabad
23197         Undisclosed                  Fresher      False    Hyderabad
23198         Undisclosed  Lead/Architect (9+ Yrs)      False    Hyderabad
23199         Undisclosed            Mid (3-5 Yrs)      False    Hyderabad
23200  Senior (10-20 LPA)         Senior (6-8 Yrs)      False    Hyderabad

                skill_domain salary_midpoint_lpa days_since_posted  \
0      Business Intelligence                 0.0              21.0
1                   AI/ML/DL                 0.0              21.0
2      Business Intelligence                 0.0              21.0
3               Data Science                 0.0              21.0
4               Data Science                 0.0              21.0
...                      ...                 ...               ...
23196           Data Science                 0.0               1.0
23197           Data Science                 0.0               1.0
23198       Data Engineering                 0.0              21.0
23199           Data Science                 0.0               0.0
23200           Data Science                13.0               1.0

      is_fresher_friendly salary_negotiable
0                   False             False
1                   False             False
2                   False             False
3                    True             False
4                   False             False
...                   ...               ...
23196               False             False
23197                True             False
23198               False             False
23199               False             False
23200               False             False

[23201 rows x 32 columns]>

In [73]:
df_final = df_final.drop(columns=['salary_raw', 'salary_min_lpa', 'salary_max_lpa', 'salary_midpoint_lpa', 'salary_disclosed', 'location', 'scraped_city', 'experience_raw', 'experience_tier', 'job_id', 'job_url', 'data_source'])

In [74]:
df_final.shape

(2683, 20)

In [5]:
df.isna().sum()

job_id                  0
job_title               0
company_name            0
company_rating          0
location                0
scraped_city            0
role_category           0
experience_raw          0
experience_min_yrs      0
experience_max_yrs      0
salary_raw              0
salary_min_lpa          0
salary_max_lpa          0
salary_disclosed        0
skills_required         0
skills_count            0
job_description         0
posted_date_raw         0
work_mode               0
company_size_bucket     0
job_url                53
data_source             0
scraped_at              0
salary_tier             0
experience_tier         0
is_senior               0
primary_city            0
skill_domain            0
salary_midpoint_lpa     0
days_since_posted       0
is_fresher_friendly     0
salary_negotiable       0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,job_id,company_rating,experience_min_yrs,experience_max_yrs,salary_min_lpa,salary_max_lpa,skills_count,salary_midpoint_lpa,days_since_posted
count,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000
mean,11601.000000,3.586449,4.135080,7.829059,1.383952,2.271790,7.604198,1.827872,15.698935
std,6697.696134,0.514250,2.933976,3.946834,4.841570,7.469383,1.456530,6.109373,7.575881
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5801.000000,3.400000,2.000000,5.000000,0.000000,0.000000,8.000000,0.000000,7.000000
50%,11601.000000,3.600000,4.000000,8.000000,0.000000,0.000000,8.000000,0.000000,21.000000
75%,17401.000000,3.800000,6.000000,10.000000,0.000000,0.000000,8.000000,0.000000,21.000000
max,23201.000000,5.000000,25.000000,31.000000,85.000000,90.000000,8.000000,87.500000,90.000000

In [13]:
df['salary_tier'].value_counts()

salary_tier
Undisclosed             20496
Senior (10-20 LPA)       1201
Leadership (20+ LPA)      463
Junior (3-6 LPA)          463
Mid (6-10 LPA)            329
Entry (<3 LPA)            249
Name: count, dtype: int64

In [15]:
df.columns.tolist()

['job_id',
 'job_title',
 'company_name',
 'company_rating',
 'location',
 'scraped_city',
 'role_category',
 'experience_raw',
 'experience_min_yrs',
 'experience_max_yrs',
 'salary_raw',
 'salary_min_lpa',
 'salary_max_lpa',
 'salary_disclosed',
 'skills_required',
 'skills_count',
 'job_description',
 'posted_date_raw',
 'work_mode',
 'company_size_bucket',
 'job_url',
 'data_source',
 'scraped_at',
 'salary_tier',
 'experience_tier',
 'is_senior',
 'primary_city',
 'skill_domain',
 'salary_midpoint_lpa',
 'days_since_posted',
 'is_fresher_friendly',
 'salary_negotiable']

In [18]:
df['salary_midpoint_lpa'].value_counts()

salary_midpoint_lpa
0.00     20435
14.00      346
22.50      183
15.00      114
27.50       93
         ...
7.20         1
4.98         1
0.17         1
12.25        1
0.35         1
Name: count, Length: 169, dtype: int64

In [21]:
df_filtered = df[df['salary_disclosed']]
df_filtered.shape
df_filtered['salary_tier'].value_counts()

salary_tier
Senior (10-20 LPA)      1201
Leadership (20+ LPA)     463
Junior (3-6 LPA)         463
Mid (6-10 LPA)           329
Entry (<3 LPA)           249
Undisclosed               63
Name: count, dtype: int64

In [22]:
df_filtered[df_filtered['salary_tier'] == 'Undisclosed']['salary_midpoint_lpa'].describe()

count    63.000000
mean      4.579683
std       6.357158
min       0.000000
25%       0.250000
50%       0.300000
75%       8.750000
max      21.000000
Name: salary_midpoint_lpa, dtype: float64

In [19]:
df.groupby('salary_disclosed')['salary_midpoint_lpa'].describe()

                    count       mean        std  min  25%   50%   75%   max
salary_disclosed
False             20433.0   0.000000   0.000000  0.0  0.0   0.0   0.0   0.0
True               2768.0  15.320972  10.302711  0.0  7.5  14.0  21.5  87.5

In [23]:
df_filtered[df_filtered['salary_tier'] == 'Undisclosed'][['job_title', 'salary_raw', 'salary_min_lpa', 'salary_max_lpa', 'salary_midpoint_lpa']].head(10)

,job_title,salary_raw,salary_min_lpa,salary_max_lpa,salary_midpoint_lpa
1056,Senior Data Engineer,0-22 Lacs PA,0.0,22.0,11.00
1346,Data Engineer,"50,000-15 Lacs PA",0.0,0.5,0.25
1929,Data Analyst,"50,000-2.5 Lacs PA",0.0,0.5,0.25
2248,Data Engineer - Support Role,0-12 Lacs PA,0.0,12.0,6.00
2338,Data Engineer,0-22 Lacs PA,0.0,22.0,11.00
3007,Data Engineer,0-24 Lacs PA,0.0,24.0,12.00
3178,Lead Data Engineer,"50,000-3 Lacs PA",0.0,0.5,0.25
3649,Data Annotation Engineer,"50,000-2.5 Lacs PA",0.0,0.5,0.25
3794,"Director Software Engineering (Data, Analytics...","60,000-1 Lacs PA",0.0,0.6,0.30
3994,Data Engineer (Spark & Scala),"60,000-1 Lacs PA",0.0,0.6,0.30

In [27]:
df_final = df_filtered[df_filtered['salary_tier'] != 'Undisclosed']
df_final.shape
df_final['salary_tier'].value_counts()

salary_tier
Senior (10-20 LPA)      1201
Leadership (20+ LPA)     463
Junior (3-6 LPA)         463
Mid (6-10 LPA)           329
Entry (<3 LPA)           249
Name: count, dtype: int64

In [28]:
df_final['salary_disclosed'].value_counts()

salary_disclosed
True    2705
Name: count, dtype: int64

In [32]:
df_final[['scraped_city']].value_counts()

scraped_city
Bangalore       488
Mumbai          397
Chennai         366
Pune            326
Noida           288
Delhi           229
Ahmedabad       189
Kolkata         179
Gurgaon         171
Remote           62
Hyderabad        10
Name: count, dtype: int64

In [34]:
df_final['work_mode'].value_counts()

work_mode
On-site    1827
Hybrid      714
Remote      164
Name: count, dtype: int64

In [45]:
df.drop(columns=['posted_date_raw','scraped_at'], inplace=True)

In [43]:
df_final[['posted_date_raw', 'scraped_at', 'days_since_posted']].head(10)

   posted_date_raw  scraped_at  days_since_posted
17       1 day ago  2025-06-10                1.0
26       1 day ago  2025-06-10                1.0
28       1 day ago  2025-06-10                1.0
29       1 day ago  2025-06-10                1.0
32       1 day ago  2025-06-10                1.0
34       1 day ago  2025-06-10                1.0
39       1 day ago  2025-06-10                1.0
43      4 days ago  2025-06-10                4.0
47      5 days ago  2025-06-10                5.0
54      5 days ago  2025-06-10                5.0

In [44]:
df_final['scraped_at'].nunique()

1

In [42]:
df_final['scraped_at'].head(10)

17    2025-06-10
26    2025-06-10
28    2025-06-10
29    2025-06-10
32    2025-06-10
34    2025-06-10
39    2025-06-10
43    2025-06-10
47    2025-06-10
54    2025-06-10
Name: scraped_at, dtype: object

In [36]:
df_final[['experience_raw', 'experience_min_yrs', 'experience_max_yrs', 'experience_tier', 'is_senior']].head(10)

,experience_raw,experience_min_yrs,experience_max_yrs,experience_tier,is_senior
17,8-12 Yrs,8.0,12.0,Senior (6-8 Yrs),False
26,5-10 Yrs,5.0,10.0,Mid (3-5 Yrs),False
28,2-7 Yrs,2.0,7.0,Junior (0-2 Yrs),False
29,6-11 Yrs,6.0,11.0,Senior (6-8 Yrs),False
32,5-10 Yrs,5.0,10.0,Mid (3-5 Yrs),False
34,6-10 Yrs,6.0,10.0,Senior (6-8 Yrs),False
39,3-6 Yrs,3.0,6.0,Mid (3-5 Yrs),False
43,5-10 Yrs,5.0,10.0,Mid (3-5 Yrs),False
47,7-10 Yrs,7.0,10.0,Senior (6-8 Yrs),False
54,3-6 Yrs,3.0,6.0,Mid (3-5 Yrs),False

In [37]:
df_final.groupby('experience_tier')[['experience_min_yrs', 'experience_max_yrs']].describe()

                        experience_min_yrs                                 \
                                     count       mean       std  min  25%
experience_tier
Fresher                              227.0   0.000000  0.000000  0.0  0.0
Junior (0-2 Yrs)                     355.0   1.597183  0.491157  1.0  1.0
Lead/Architect (9+ Yrs)              145.0  10.979310  2.174566  9.0  9.0
Mid (3-5 Yrs)                       1266.0   4.075039  0.786181  3.0  3.0
Senior (6-8 Yrs)                     712.0   6.803371  0.844001  6.0  6.0

                                          experience_max_yrs             \
                          50%   75%   max              count       mean
experience_tier
Fresher                   0.0   0.0   0.0              227.0   2.348018
Junior (0-2 Yrs)          2.0   2.0   2.0              355.0   5.098592
Lead/Architect (9+ Yrs)  10.0  12.0  20.0              145.0  16.627586
Mid (3-5 Yrs)             4.0   5.0   5.0             1266.0   8.235387
Senior (6-8 Yrs)          7.0   8.0   8.0              712.0  10.952247


                              std  min   25%   50%   75%   max
experience_tier
Fresher                  2.515005  0.0   0.0   2.0   4.0   8.0
Junior (0-2 Yrs)         2.829201  2.0   4.0   5.0   6.0  31.0
Lead/Architect (9+ Yrs)  4.174900  8.0  14.0  17.0  20.0  25.0
Mid (3-5 Yrs)            1.795439  4.0   8.0   8.0   9.0  30.0
Senior (6-8 Yrs)         1.595694  8.0  10.0  11.0  12.0  17.0

In [46]:
df_final.groupby('salary_tier')['days_since_posted'].mean()

salary_tier
Entry (<3 LPA)          14.955823
Junior (3-6 LPA)        10.557235
Leadership (20+ LPA)    10.401728
Mid (6-10 LPA)          11.142857
Senior (10-20 LPA)      15.644463
Name: days_since_posted, dtype: float64

In [39]:
df_final.groupby('is_senior')[['experience_min_yrs', 'experience_max_yrs']].describe()

          experience_min_yrs                                                \
                       count      mean       std  min  25%  50%  75%   max
is_senior
False                 2169.0  4.305671  2.572056  0.0  3.0  4.0  6.0  20.0
True                   536.0  5.266791  3.056126  0.0  3.0  5.0  7.0  16.0

          experience_max_yrs
                       count      mean       std  min  25%   50%   75%   max
is_senior
False                 2169.0  8.259106  3.654622  0.0  6.0   8.0  10.0  31.0
True                   536.0  9.447761  4.267797  0.0  7.0  10.0  12.0  24.0

In [47]:
df_final.duplicated().sum()

np.int64(0)

In [59]:
df_final[['skills_count']].value_counts()
df_final[df_final['skills_count'] == 0]['skills_required'].head(20)

416     Not Available
617     Not Available
678     Not Available
800     Not Available
991     Not Available
1008    Not Available
1010    Not Available
1038    Not Available
1136    Not Available
1137    Not Available
1161    Not Available
1174    Not Available
1316    Not Available
1321    Not Available
1387    Not Available
1448    Not Available
1478    Not Available
1616    Not Available
1726    Not Available
1824    Not Available
Name: skills_required, dtype: object

In [60]:
df_final[df_final['skills_count'] == 0]['salary_tier'].value_counts(normalize=True)

salary_tier
Senior (10-20 LPA)      0.852861
Entry (<3 LPA)          0.117166
Leadership (20+ LPA)    0.010899
Mid (6-10 LPA)          0.010899
Junior (3-6 LPA)        0.008174
Name: proportion, dtype: float64

In [62]:
df_final[['job_title', 'company_name', 'role_category', 'company_size_bucket', 'skill_domain', 'is_fresher_friendly']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 2705 entries, 17 to 23200
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            2705 non-null   object
 1   company_name         2705 non-null   object
 2   role_category        2705 non-null   object
 3   company_size_bucket  2705 non-null   object
 4   skill_domain         2705 non-null   object
 5   is_fresher_friendly  2705 non-null   bool
dtypes: bool(1), object(5)
memory usage: 129.4+ KB

In [63]:
df_final[df_final['experience_max_yrs'] > 20][['job_title', 'experience_raw', 'experience_min_yrs', 'experience_max_yrs']]

,job_title,experience_raw,experience_min_yrs,experience_max_yrs
512,Senior Manager Data Scientist,12-21 Yrs,12.0,21.0
1234,Practice Lead-Data and Advanced Analytics,15-24 Yrs,15.0,24.0
3154,Practice Lead-Data and Advanced Analytics,15-24 Yrs,15.0,24.0
4044,Snowflake Data Architect_14+ years_Chennai/PAN...,15-22 Yrs,15.0,22.0
4860,Gcp Data Engineer (Freelance Domain Recruitmen...,15-24 Yrs,15.0,24.0
6489,Data Analyst,14-22 Yrs,14.0,22.0
6973,Walk-In Any Fresher's/Expr-MIS Executive/Repor...,02 Jun - 31 Jul,2.0,31.0
6974,Walk-In Any Fresher's/Expr-MIS Executive/Repor...,02 Jun - 31 Jul,2.0,31.0
8473,Walk-in || Mis Executive,09 Jun - 21 Jun,9.0,21.0
10177,General Manager Technical- Beverage/Breweries ...,15-24 Yrs,15.0,24.0
10490,Walk-in || Account Executive,01 Jun - 30 Jun,1.0,30.0
11634,AI/ Machine Learning Managers/ Architects/ SM/...,11-21 Yrs,11.0,21.0
11951,Practice Lead Catastrophe Modelling and Exposure,15-24 Yrs,15.0,24.0
12259,AI/ Machine Learning Managers/ Architects/ SM/...,11-21 Yrs,11.0,21.0
12618,AI/ Machine Learning Managers/ Architects/ SM/...,11-21 Yrs,11.0,21.0
12833,AI/ Machine Learning Managers/ Architects/ SM/...,11-21 Yrs,11.0,21.0
13219,Artificial Intelligence Architect,20-22 Yrs,20.0,22.0
13426,Walk-in || Production Associate / Apprentice T...,05 Jun - 30 Jun,5.0,30.0
13937,RTR Transformation-IBM-Hyderbad/Bangalore/Noid...,14-24 Yrs,14.0,24.0
14464,Walk-in || Production Associate / Apprentice T...,05 Jun - 30 Jun,5.0,30.0
16675,Oracle EPM Architect,10-25 Yrs,10.0,25.0
16921,Oracle EPM Functional Consultant,5-25 Yrs,5.0,25.0
21055,Sap Abap Consultant,12-22 Yrs,12.0,22.0

In [64]:
(df_final['experience_min_yrs'] > df_final['experience_max_yrs']).sum()

np.int64(12)

In [65]:
df_final[df_final['experience_min_yrs'] > df_final['experience_max_yrs']][['job_title', 'experience_raw', 'experience_min_yrs', 'experience_max_yrs']]

,job_title,experience_raw,experience_min_yrs,experience_max_yrs
764,Walk-in || Big Data Engineer,13 Jun,13.0,8.0
3608,Walk-in || Gcp Data Engineer- walkin drive -ch...,13 Jun,13.0,8.0
3611,Walk- in interview GCP Data Engineer-June 13th,13 Jun,13.0,8.0
7360,Walk-in || Business Analyst (Banking),17 May - 15 Aug,17.0,15.0
12471,Walk-in || Machine Learning Engineer,13 Jun,13.0,8.0
12505,Walk-in || Data Analyst/AI-ML,11 Jun - 10 Jul,11.0,10.0
12677,Walk-in || Artificial Intelligence Developer,13 Jun,13.0,8.0
13227,Walk-in || Data Analyst/AI-ML,11 Jun - 10 Jul,11.0,10.0
13986,Walk-in || Software Developer - 2,13 Jun,13.0,8.0
18090,"Walk-in || Business Intelligence Analyst, Paid...",13 Jun,13.0,8.0
22426,Walkin Drive -Python AI developer,13 Jun,13.0,8.0
23032,Walk-in || Dot Net Software Developer,13 Jun,13.0,8.0

In [67]:
df_final = df_final[~df_final['job_title'].str.contains('Walk-in', case=False, na=False)]

In [68]:
df_final.shape

(2683, 32)

In [69]:
df_final[['experience_min_yrs','experience_max_yrs']].describe()

       experience_min_yrs  experience_max_yrs
count         2683.000000         2683.000000
mean             4.457324            8.433470
std              2.648418            3.682338
min              0.000000            0.000000
25%              3.000000            6.000000
50%              4.000000            8.000000
75%              6.000000           10.000000
max             20.000000           25.000000

In [66]:
df_final[df_final['job_title'].str.contains('Walk-in', case=False, na=False)][['job_title', 'experience_raw', 'experience_min_yrs', 'experience_max_yrs']]

,job_title,experience_raw,experience_min_yrs,experience_max_yrs
764,Walk-in || Big Data Engineer,13 Jun,13.0,8.0
1563,Walk-in || Business Analyst,09 Jun - 19 Jun,9.0,19.0
2981,Walk-In Interview - Data Analyst,10 Jun - 11 Jun,10.0,11.0
3608,Walk-in || Gcp Data Engineer- walkin drive -ch...,13 Jun,13.0,8.0
5331,Walk-in || Analyst,09 Jun - 20 Jun,9.0,20.0
6973,Walk-In Any Fresher's/Expr-MIS Executive/Repor...,02 Jun - 31 Jul,2.0,31.0
6974,Walk-In Any Fresher's/Expr-MIS Executive/Repor...,02 Jun - 31 Jul,2.0,31.0
7360,Walk-in || Business Analyst (Banking),17 May - 15 Aug,17.0,15.0
8473,Walk-in || Mis Executive,09 Jun - 21 Jun,9.0,21.0
9200,Walk-in || Senior Gis Executive,02 Jun - 10 Jun,2.0,10.0
9556,Walk-in || Spinny is Hiring For MIS Executive ...,09 Jun - 10 Jun,9.0,10.0
10490,Walk-in || Account Executive,01 Jun - 30 Jun,1.0,30.0
12471,Walk-in || Machine Learning Engineer,13 Jun,13.0,8.0
12505,Walk-in || Data Analyst/AI-ML,11 Jun - 10 Jul,11.0,10.0
12677,Walk-in || Artificial Intelligence Developer,13 Jun,13.0,8.0
13227,Walk-in || Data Analyst/AI-ML,11 Jun - 10 Jul,11.0,10.0
13426,Walk-in || Production Associate / Apprentice T...,05 Jun - 30 Jun,5.0,30.0
13986,Walk-in || Software Developer - 2,13 Jun,13.0,8.0
14464,Walk-in || Production Associate / Apprentice T...,05 Jun - 30 Jun,5.0,30.0
16689,Walk-in || Bi Administrator,10 Jun - 17 Jun,10.0,17.0
18090,"Walk-in || Business Intelligence Analyst, Paid...",13 Jun,13.0,8.0
23032,Walk-in || Dot Net Software Developer,13 Jun,13.0,8.0

In [61]:
df_final[['experience_min_yrs', 'experience_max_yrs', 'company_rating', 'skills_count', 'days_since_posted']].describe()

,experience_min_yrs,experience_max_yrs,company_rating,skills_count,days_since_posted
count,2705.000000,2705.000000,2705.000000,2705.000000,2705.000000
mean,4.496118,8.494640,3.584067,6.626617,13.265434
std,2.701647,3.812748,0.428783,2.746493,9.819891
min,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.000000,6.000000,3.500000,7.000000,6.000000
50%,4.000000,8.000000,3.600000,8.000000,14.000000
75%,6.000000,10.000000,3.600000,8.000000,21.000000
max,20.000000,31.000000,5.000000,8.000000,90.000000